### PR TITLE
Hotfix pong and Fixed hud

### LINKED ISSUE #123: HUD and recent changes in window resizability
Everything from `engi.Background` till `engi.HUDGround-1` works. From `engi.HUDGround` and up, things are still a bit messed up.

### PR DESCRIPTION
**Pull request by EtienneBruines**
Updated HUD rendering, which fixed #123.

Also added a line to the pong demo to ensure it scales on resizing the window.

Feel free to review and merge @paked @matiwinnetou

### CODE REVIEW

File: assets.go [hunk 1]
```diff
@@ -320,8 +321,8 @@ varying vec2 var_TexCoords;
 void main() {
   var_Color = in_Color;
   var_TexCoords = in_TexCoords;
-  gl_Position = vec4((4.0*in_Position.x) / uf_Projection.x - 2.0,
-  					 (4.0*in_Position.y) / -uf_Projection.y + 2.0, 0, 2.0);
+  gl_Position = vec4(in_Position.x / uf_Projection.x - 1.0,
+  					 in_Position.y / -uf_Projection.y + 1.0, 0, 1.0);
```
Comment (EtienneBruines) [inline assets.go]: Makes more sense this way. `uf_Projection` is most often half of the screen, which is exactly what you'd expect if you were to normalize it. The `+/- 1.0` are for alignment.

**Comment by paked** [comment]
Tahnks!
